//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using Library_Management.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BillCustomerReturnBookLibrary : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillCustomerReturnBookLibrary()
        {
            this.ListBookCustomerReturnBookLibraries = new HashSet<ListBookCustomerReturnBookLibrary>();
        }

        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private int _IdHuman;
        public int IdHuman { get => _IdHuman; set { _IdHuman = value; OnPropertyChanged(); } }

        private int _IdStaff;
        public int IdStaff { get => _IdStaff; set { _IdStaff = value; OnPropertyChanged(); } }

        private System.DateTime _DateOfRepayment;
        public System.DateTime DateOfRepayment { get => _DateOfRepayment; set { _DateOfRepayment = value; OnPropertyChanged(); } }

        private Nullable<double> _AllTheDepositAmount;
        public Nullable<double> AllTheDepositAmount { get => _AllTheDepositAmount; set { _AllTheDepositAmount = value; OnPropertyChanged(); } }

        private Nullable<double> _CashReceived;
        public Nullable<double> CashReceived { get => _CashReceived; set { _CashReceived = value; OnPropertyChanged(); } }

        private Nullable<double> _CustomerFined;
        public Nullable<double> CustomerFined { get => _CustomerFined; set { _CustomerFined = value; OnPropertyChanged(); } }

        private Nullable<double> _AllFines;
        public Nullable<double> AllFines { get => _AllFines; set { _AllFines = value; OnPropertyChanged(); } }

        private int _IdStatusBill;
        public int IdStatusBill { get => _IdStatusBill; set { _IdStatusBill = value; OnPropertyChanged(); } }

        private string _Note;
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }
        public Nullable<int> CountDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListBookCustomerReturnBookLibrary> ListBookCustomerReturnBookLibraries { get; set; }
        public virtual Human Human { get; set; }
        public virtual UserStaff UserStaff { get; set; }
        public virtual StatusBill StatusBill { get; set; }
    }
}
