//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using Library_Management.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BookSubject : BaseViewModel
    {
        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }

        private Nullable<int> _ScoreInputSubject;
        public Nullable<int> ScoreInputSubject { get => _ScoreInputSubject; set { _ScoreInputSubject = value; OnPropertyChanged(); } }

        private Nullable<int> _ScoreOuputSubject;
        public Nullable<int> ScoreOuputSubject { get => _ScoreOuputSubject; set { _ScoreOuputSubject = value; OnPropertyChanged(); } }

        private string _Note;
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }

        private Nullable<int> _CountDelete;
        public Nullable<int> CountDelete { get => _CountDelete; set { _CountDelete = value; OnPropertyChanged(); } }
    }
}
