//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAvailable_vi
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public int BorrowingIdHuman { get; set; }
        public string BookSubject { get; set; }
        public string Author { get; set; }
        public string Language { get; set; }
        public string Publisher { get; set; }
        public string Status { get; set; }
        public string UrlImageBook { get; set; }
        public string Note { get; set; }
    }
}
