//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using Library_Management.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowBook : BaseViewModel
    {
        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private int _IdHuman;
        public int IdHuman { get => _IdHuman; set { _IdHuman = value; OnPropertyChanged(); } }

        private int _IdBook;
        public int IdBook { get => _IdBook; set { _IdBook = value; OnPropertyChanged(); } }

        private System.DateTime _DateBorrowed;
        public System.DateTime DateBorrowed { get => _DateBorrowed; set { _DateBorrowed = value; OnPropertyChanged(); } }

        private System.DateTime _DueDate;
        public System.DateTime DueDate { get => _DueDate; set { _DueDate = value; OnPropertyChanged(); } }

        private int _IdStatus;
        public int IdStatus { get => _IdStatus; set { _IdStatus = value; OnPropertyChanged(); } }

        private int _IdFined;
        public int IdFined { get => _IdFined; set { _IdFined = value; OnPropertyChanged(); } }

        private string _Color;
        public string Color { get => _Color; set { _Color = value; OnPropertyChanged(); } }

        private double _ContractualFine;
        public double ContractualFine { get => _ContractualFine; set { _ContractualFine = value; OnPropertyChanged(); } }

        private string _Note;
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }

        private Nullable<int> _CountDelete;
        public Nullable<int> CountDelete { get => _CountDelete; set { _CountDelete = value; OnPropertyChanged(); } }
    
        public virtual Book Book { get; set; }
        public virtual Fined Fined { get; set; }
        public virtual Human Human { get; set; }
        public virtual Status Status { get; set; }
    }
}
