//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using Library_Management.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryCreateTimeTable : BaseViewModel
    {
        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private int _IdUserStaff;
        public int IdUserStaff { get => _IdUserStaff; set { _IdUserStaff = value; OnPropertyChanged(); } }

        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }

        private System.DateTime _DateCreate;
        public System.DateTime DateCreate { get => _DateCreate; set { _DateCreate = value; OnPropertyChanged(); } }
        public virtual UserStaff UserStaff { get; set; }
    }
}
