//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using Library_Management.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Human : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Human()
        {
            this.BillBookOfCustomers = new HashSet<BillBookOfCustomer>();
            this.BillBookOfHumen = new HashSet<BillBookOfHuman>();
            this.BillCustomerReturnBookLibraries = new HashSet<BillCustomerReturnBookLibrary>();
            this.BillReturnBookHumen = new HashSet<BillReturnBookHuman>();
            this.Books = new HashSet<Book>();
            this.BorrowBooks = new HashSet<BorrowBook>();
            this.UserHumen = new HashSet<UserHuman>();
            this.UserStaffs = new HashSet<UserStaff>();
            this.TimeTables = new HashSet<TimeTable>();
            this.TimeTables1 = new HashSet<TimeTable>();
            this.TimeTables2 = new HashSet<TimeTable>();
            this.TimeTables3 = new HashSet<TimeTable>();
            this.TimeTables4 = new HashSet<TimeTable>();
            this.TimeTables5 = new HashSet<TimeTable>();
            this.TimeTables6 = new HashSet<TimeTable>();
        }

        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private string _MS;
        public string MS { get => _MS; set { _MS = value; OnPropertyChanged(); } }

        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }

        private System.DateTime _DateOfBirth;
        public System.DateTime DateOfBirth { get => _DateOfBirth; set { _DateOfBirth = value; OnPropertyChanged(); } }

        private int _IdGender;
        public int IdGender { get => _IdGender; set { _IdGender = value; OnPropertyChanged(); } }

        private int _IdAuthorityHuman;
        public int IdAuthorityHuman { get => _IdAuthorityHuman; set { _IdAuthorityHuman = value; OnPropertyChanged(); } }

        private string _Address;
        public string Address { get => _Address; set { _Address = value; OnPropertyChanged(); } }

        private string _Phone;
        public string Phone { get => _Phone; set { _Phone = value; OnPropertyChanged(); } }

        private string _Email;
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }

        private string _UrlAvatarHuman;
        public string UrlAvatarHuman { get => _UrlAvatarHuman; set { _UrlAvatarHuman = value; OnPropertyChanged(); } }

        private Nullable<Double> _Score;
        public Nullable<Double> Score { get => _Score; set { _Score = value; OnPropertyChanged(); } }

        private Nullable<double> _Forfeit;
        public Nullable<double> Forfeit { get => _Forfeit; set { _Forfeit = value; OnPropertyChanged(); } }

        private Nullable<double> _PayFine;
        public Nullable<double> PayFine { get => _PayFine; set { _PayFine = value; OnPropertyChanged(); } }

        private Nullable<double> _Compensation;
        public Nullable<double> Compensation { get => _Compensation; set { _Compensation = value; OnPropertyChanged(); } }

        private string _Note;
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }

        private Nullable<int> _CountDelete;
        public Nullable<int> CountDelete { get => _CountDelete; set { _CountDelete = value; OnPropertyChanged(); } }
    
        public virtual AuthorityHuman AuthorityHuman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillBookOfCustomer> BillBookOfCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillBookOfHuman> BillBookOfHumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillCustomerReturnBookLibrary> BillCustomerReturnBookLibraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReturnBookHuman> BillReturnBookHumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowBook> BorrowBooks { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserHuman> UserHumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserStaff> UserStaffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables6 { get; set; }
    }
}
