//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human_vi
    {
        public int Id { get; set; }
        public string MS { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Authority { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public Nullable<double> Forfeit { get; set; }
        public Nullable<double> PayFine { get; set; }
        public string Note { get; set; }
    }
}
