//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusBill()
        {
            this.BillBookOfCustomers = new HashSet<BillBookOfCustomer>();
            this.BillBookOfHumen = new HashSet<BillBookOfHuman>();
            this.BillCustomerReturnBookLibraries = new HashSet<BillCustomerReturnBookLibrary>();
            this.BillReturnBookHumen = new HashSet<BillReturnBookHuman>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> CountDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillBookOfCustomer> BillBookOfCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillBookOfHuman> BillBookOfHumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillCustomerReturnBookLibrary> BillCustomerReturnBookLibraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReturnBookHuman> BillReturnBookHumen { get; set; }
    }
}
