//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using Library_Management.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable : BaseViewModel
    {
        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private int _IdTimeLine;
        public int IdTimeLine { get => _IdTimeLine; set { _IdTimeLine = value; OnPropertyChanged(); } }

        private int _IdAuthorityStaff;
        public int IdAuthorityStaff { get => _IdAuthorityStaff; set { _IdAuthorityStaff = value; OnPropertyChanged(); } }

        private int _IdHumanSunday;
        public int IdHumanSunday { get => _IdHumanSunday; set { _IdHumanSunday = value; OnPropertyChanged(); } }

        private string _CheckIdHumanSundayWork;
        public string CheckIdHumanSundayWork { get => _CheckIdHumanSundayWork; set { _CheckIdHumanSundayWork = value; OnPropertyChanged(); } }

        private int _IdHumanMonday;
        public int IdHumanMonday { get => _IdHumanMonday; set { _IdHumanMonday = value; OnPropertyChanged(); } }

        private string _CheckIdHumanMondayWork;
        public string CheckIdHumanMondayWork { get => _CheckIdHumanMondayWork; set { _CheckIdHumanMondayWork = value; OnPropertyChanged(); } }

        private int _IdHumanTuesday;
        public int IdHumanTuesday { get => _IdHumanTuesday; set { _IdHumanTuesday = value; OnPropertyChanged(); } }

        private string _CheckIdHumanTuesdayWork;
        public string CheckIdHumanTuesdayWork { get => _CheckIdHumanTuesdayWork; set { _CheckIdHumanTuesdayWork = value; OnPropertyChanged(); } }

        private int _IdHumanWednesday;
        public int IdHumanWednesday { get => _IdHumanWednesday; set { _IdHumanWednesday = value; OnPropertyChanged(); } }

        private string _CheckIdHumanWednesdayWork;
        public string CheckIdHumanWednesdayWork { get => _CheckIdHumanWednesdayWork; set { _CheckIdHumanWednesdayWork = value; OnPropertyChanged(); } }

        private int _IdHumanThursday;
        public int IdHumanThursday { get => _IdHumanThursday; set { _IdHumanThursday = value; OnPropertyChanged(); } }

        private string _CheckIdHumanThursdayWork;
        public string CheckIdHumanThursdayWork { get => _CheckIdHumanThursdayWork; set { _CheckIdHumanThursdayWork = value; OnPropertyChanged(); } }

        private int _IdHumanFriday;
        public int IdHumanFriday { get => _IdHumanFriday; set { _IdHumanFriday = value; OnPropertyChanged(); } }

        private string _CheckIdHumanFridayWork;
        public string CheckIdHumanFridayWork { get => _CheckIdHumanFridayWork; set { _CheckIdHumanFridayWork = value; OnPropertyChanged(); } }

        private int _IdHumanSaturday;
        public int IdHumanSaturday { get => _IdHumanSaturday; set { _IdHumanSaturday = value; OnPropertyChanged(); } }

        private string _CheckIdHumanSaturdayWork;
        public string CheckIdHumanSaturdayWork { get => _CheckIdHumanSaturdayWork; set { _CheckIdHumanSaturdayWork = value; OnPropertyChanged(); } }

        private Nullable<int> _CountDelete;
        public Nullable<int> CountDelete { get => _CountDelete; set { _CountDelete = value; OnPropertyChanged(); } }

        private System.DateTime _InnitiatedDate;
        public System.DateTime InnitiatedDate { get => _InnitiatedDate; set { _InnitiatedDate = value; OnPropertyChanged(); } }

        private System.DateTime _EndDate;
        public System.DateTime EndDate { get => _EndDate; set { _EndDate = value; OnPropertyChanged(); } }
        
    
        public virtual AuthorityStaff AuthorityStaff { get; set; }
        public virtual Human Human { get; set; }
        public virtual Human Human1 { get; set; }
        public virtual Human Human2 { get; set; }
        public virtual Human Human3 { get; set; }
        public virtual Human Human4 { get; set; }
        public virtual Human Human5 { get; set; }
        public virtual Human Human6 { get; set; }
        public virtual TimeLine TimeLine { get; set; }
    }
}
