//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Model
{
    using Library_Management.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class UserStaff : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserStaff()
        {
            this.BillBookOfCustomers = new HashSet<BillBookOfCustomer>();
            this.BillBookOfHumen = new HashSet<BillBookOfHuman>();
            this.BillCustomerReturnBookLibraries = new HashSet<BillCustomerReturnBookLibrary>();
            this.BillReturnBookHumen = new HashSet<BillReturnBookHuman>();
            this.HistoryCreateTimeTables = new HashSet<HistoryCreateTimeTable>();
        }

        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private int _IdHuman;
        public int IdHuman { get => _IdHuman; set { _IdHuman = value; OnPropertyChanged(); } }

        private string _UserName;
        public string UserName { get => _UserName; set { _UserName = value; OnPropertyChanged(); } }

        private string _Password;
        public string Password { get => _Password; set { _Password = value; OnPropertyChanged(); } }

        private int _IdAuthorityStaff;
        public int IdAuthorityStaff { get => _IdAuthorityStaff; set { _IdAuthorityStaff = value; OnPropertyChanged(); } }

        private string _Note;
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }

        private Nullable<int> _ScoreInputBook;
        public Nullable<int> ScoreInputBook { get => _ScoreInputBook; set { _ScoreInputBook = value; OnPropertyChanged(); } }

        private Nullable<int> _ScoreOuputBook;
        public Nullable<int> ScoreOuputBook { get => _ScoreOuputBook; set { _ScoreOuputBook = value; OnPropertyChanged(); } }

        private Nullable<int> _CountDelete;
        public Nullable<int> CountDelete { get => _CountDelete; set { _CountDelete = value; OnPropertyChanged(); } }

    
        public virtual AuthorityStaff AuthorityStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillBookOfCustomer> BillBookOfCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillBookOfHuman> BillBookOfHumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillCustomerReturnBookLibrary> BillCustomerReturnBookLibraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReturnBookHuman> BillReturnBookHumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryCreateTimeTable> HistoryCreateTimeTables { get; set; }
        public virtual Human Human { get; set; }
    }
}
